# Generated by Django 4.1.7 on 2024-04-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestSerialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_msg", models.CharField(max_length=2000)),
                ("msg_type", models.IntegerField()),
                ("flags", models.IntegerField()),
                ("seq_num", models.IntegerField()),
                ("msg_gen_ts", models.CharField(max_length=200)),
                ("cell_id", models.IntegerField()),
                ("cell_id_ts", models.CharField(max_length=200)),
                ("actual_temp", models.IntegerField()),
                ("trumi_st", models.IntegerField()),
                ("trumi_st_upd_count", models.IntegerField()),
                ("trumi_st_upd_ts", models.CharField(max_length=200)),
                ("payload", models.CharField(max_length=2000)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="n5_lgr_backend.testdevice",
                    ),
                ),
            ],
        ),
    ]
