# Generated by Django 4.1.7 on 2024-04-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0002_alter_testserialdata_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testserialdata",
            name="device_id",
        ),
        migrations.AddField(
            model_name="testserialdata",
            name="device_id",
            field=models.ManyToManyField(to="n5_lgr_backend.testdevice"),
        ),
    ]
