# Generated by Django 4.1.7 on 2024-04-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0003_remove_testserialdata_device_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testserialdata",
            name="device_id",
        ),
        migrations.AddField(
            model_name="testserialdata",
            name="device_id",
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
