# Generated by Django 4.1.7 on 2024-04-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0004_remove_testserialdata_device_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testserialdata",
            name="lgr_msg_ts",
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
