# Generated by Django 4.1.7 on 2024-04-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0005_testserialdata_lgr_msg_ts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testserialdata",
            options={"ordering": ("create_at",)},
        ),
    ]
