# Generated by Django 4.1.7 on 2024-04-09 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0006_alter_testserialdata_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testserialdata",
            options={"ordering": ("-create_at",)},
        ),
        migrations.AlterField(
            model_name="testserialdata",
            name="device_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="n5_lgr_backend.testdevice",
            ),
        ),
    ]
