# Generated by Django 4.1.7 on 2024-04-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0008_alter_testserialdata_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testserialdata",
            name="device_id",
        ),
        migrations.AddField(
            model_name="testserialdata",
            name="device_poo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="n5_lgr_backend.testdevice",
            ),
            preserve_default=False,
        ),
    ]
