# Generated by Django 4.1.7 on 2024-04-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0009_remove_testserialdata_device_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testserialdata",
            old_name="device_poo",
            new_name="device_serial",
        ),
    ]
