# Generated by Django 4.1.7 on 2024-04-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0010_rename_device_poo_testserialdata_device_serial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testdevice",
            name="serial",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
