# Generated by Django 4.1.7 on 2024-04-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0011_alter_testdevice_serial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testserialdata",
            name="msg_type",
            field=models.CharField(max_length=200),
        ),
    ]
