# Generated by Django 4.1.7 on 2024-04-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0012_alter_testserialdata_msg_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testserialdata",
            name="cell_id",
            field=models.CharField(max_length=200),
        ),
    ]
