# Generated by Django 4.1.7 on 2024-04-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0014_alter_testserialdata_trumi_st"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testserialdata",
            name="actual_temp",
            field=models.CharField(max_length=5),
        ),
    ]
