# Generated by Django 4.1.7 on 2024-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("n5_lgr_backend", "0015_alter_testserialdata_actual_temp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testserialdata",
            name="flags",
            field=models.CharField(max_length=50),
        ),
    ]
